name: CI
run-name: Build Component Registry front end with npm
on: [push]
jobs:
  npm-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out the repository
        uses: actions/checkout@v5
      - name: Run the build script
        run: bash build.sh install build
